#!/bin/bash
#erl -pa ebin/ deps/*/ebin -noshell -eval 'properjs:main([])' -s erlang halt
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ERL_LIBS="$DIR/ebin;$DIR/deps/erlang_js/ebin" $DIR/properjs.escript "$@"
